import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import styles from "./layout.module.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Configure Poppins
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // Choose the weights you need
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html 
      lang="en" 
      className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable}`}
    >
      <body>
        <nav className={styles.nav}>
          <article>
            <a href="/">
            <Image
            src={"/icons/logo.png"}
            height={50}
            width={50}
            alt="logo"
            />
            AgroRover
            </a>
          </article>
          <ul>
            <li>
            <a href="/monitoring">
               <Image height={50} width={50} alt="dashboard" src={"/icons/dashboard.png"} /> <h3>Dashboard</h3>
            </a>
            </li>
            
            <li>
              <a href="/alerts">
              <Image height={50} width={50} alt="alerts" src={"/icons/alert.png"} /> 
              <h3>Alerts</h3>
              </a>
            </li>

            <li>
              <a href="/map">
              <Image height={50} width={50} alt="field map" src={"/icons/map.png"} /> 
              <h3>Field map</h3>
              </a>
            </li>

            <span>Monitoring</span>
            
            <li>
              <a href="/monitoring">
              <Image height={50} width={50} alt="Soil sensors" src={"/icons/sensors.png"} /> 
              <h3>Soil Sensors</h3>
              </a>
            </li>

            <li>
              <a href="/monitoring">
                <Image height={50} width={50} alt="Irrigation" src={"/icons/Irrigation.png"} />  
                <h3>Irrigation</h3>
              </a>
            </li>


            <span>Analytics</span>
            
            <li>
              <a href="/chatbot">
              <Image height={50} width={50} alt="AI assistant" src={"/icons/ai.png"} /> 
              <h3>AI assistant</h3>
              </a>
            </li>
            
          </ul>
        </nav>
        <div>
          <header className={styles.header}>
            <article>
              <Image src={"/icons/location.png"} height={30} width={30} alt="location" />
              <h3>Rabat, Ma</h3>
            </article>
            <article>
              <Image src={"/icons/calendar.png"} height={30} width={30} alt="date" />
              <h3>May 21, 2026</h3>
            </article>
          </header>
        {children}
        </div>
      </body>
    </html>
  );
}